### ISSUE TITLE
Download by split

### ISSUE THREAD

**Issue by ascourtas** [MLMI2-CSSI/foundry#378] opened 2023-06-27 19:45 UTC
_As a Data Consumer, I may not want to download the whole dataset when I run `f.load()`, but rather just download a subset of splits_

Expand upon the load-by-split functionality in #344(which requires all parts of the dataset to be downloaded) to include the option to download the dataset by split (using either Globus or HTTPS).

# Assumptions:
1. 
2. 

# Acceptance Criteria
Given..., when..., then...

**Comment by kjschmidt913** [comment] 2024-01-25 22:11
I think this is a duplicate of #401 so closing this one

**Closed by kjschmidt913** 2024-01-25 22:11 UTC
