### ISSUE TITLE
Investigate continuous docs integration

### ISSUE THREAD

**Issue by ascourtas** [MLMI2-CSSI/foundry#369] opened 2023-06-13 17:32 UTC
_As a User, I want the docs to always reflect the latest work_

Look into continuous docs integration (ie docs are automatically and continuously updated) for Foundry. 

# Assumptions:
1. 
2. 

# Acceptance Criteria
Given..., when..., then...

**Comment by kjschmidt913** [comment] 2024-01-29 17:49
duplicate of #410

**Closed by kjschmidt913** 2024-01-29 17:49 UTC
Labels: documentation and examples
